### ISSUE TITLE
Include FindTBB.cmake as part of package

### ISSUE THREAD

**Issue by johnlees** [santeripuranen/SpydrPick#2]
I have TBB installed through anaconda (which for me is under `/Users/leesj01/anaconda3/`). I can use `-DBoost_INCLUDE_DIR` options to cmake to specify this for boost, but could not find an equivalent for TBB.

When I turned off the quiet mode in `tbb.cmake` at line 16, I got the following error message:
```
CMake Warning at externals/tbb.cmake:19 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.
```

Is the solution to this to include `FindTBB.cmake` with this repository?

Thanks!
John

**Comment by santeripuranen** [comment]
Hi John,

That would certainly be _a_ solution, but for now there's for example a PD version of `FindTBB.cmake` available under the [VTK](https://github.com/Kitware/VTK/blob/master/CMake/FindTBB.cmake) project that you can try to use.

Regards,
Santeri

**Comment by johnlees** [comment]
Ok, thanks - that's now working and I have a Makefile.
Using GCC 8.2.0 on OS X I get errors:
```
/Users/leesj01/Documents/Postdoc/SpydrPick/SpydrPick/externals/apegrunt/src/Apegrunt_options.cpp:30:1: error: 'uint' does not name a type; did you mean 'rint'?
 uint Apegrunt_options_base::s_state = 1;
 ^~~~
 rint
```
Which is probably caused by missing header includes (in this case `stdint.h` or `cstdint` I believe). I had some of the same problems with the previous prototype version, which makes me think this may be platform specific.

**Comment by santeripuranen** [comment]
Yeah, `uint` is a `typedef unsigned int uint;` in `types.h` that on my system lives in `/usr/include/sys/`. I'm not sure where/how it comes #included into this project.. `Apegrunt_options_base::s_state` is actually not used at the moment, so could just as well remove it, or then change it into a `std::size_t`.

**Comment by johnlees** [comment]
I think I might have found a way around this using clang instead of gcc - bear with me and I'll see if I can get it to work this way!

**Comment by santeripuranen** [comment]
I commented out said variable and the function associated with it. Please do a `git submodule update --recursive --remote` in the main project folder or `git pull origin development` in `externals/apegrunt`.
