### ISSUE TITLE
Value for ld_dist

### ISSUE THREAD

**Issue by herber4** [santeripuranen/SpydrPick#7]
Hello! 

Just a question. 

What value is typically used for the ld_dist in the gwes_plot? 

What do you recommend? 

Best

Austin

**Comment by jurikuronen** [comment]
Hi Austin,

It can vary a lot, based on your data. For bacterial genomes, it is typically in the 500-20000 bp range. You can try determining it "by eye" after plotting initially with `ld_dist <- 0`. This setting then draws a vertical dashed line at the specified location. 

Note that if you ran SpydrPick without specifying the linkage disequilibrium (LD) threshold distance option --ld-threshold=<int:distance>, then it is likely that the majority of the outliers outputted by SpydrPick are short-distance pairs that have a lot of linkage disequilibrium. Then likely the calculated outlier and extreme outlier thresholds are incorrect and the GWES plot would miss most of the interesting couplings.

If so, you can try determining the `ld_dist` as suggested above and re-run SpydrPick or manually post-process the full results by your own choices.

Best regards
Juri Kuronen
