### ISSUE TITLE
Failed to compile and install 

### ISSUE THREAD

**Issue by dana33335446** [santeripuranen/SpydrPick#8]
Hi Santeri,

SpydrPick is a great tool for co-selection study, but I failed to compile and install our tool.

The errors pop out when did "cmake .." in MacOS, here is the information:

> cmake ..
> SPYDRPICK_DEPENDENCIES setup: check for Boost
> SPYDRPICK_DEPENDENCIES setup: found Boost v1.78.0
>                               include dir: /usr/local/include
>                               libraries: Boost::program_options;Boost::filesystem;Boost::iostreams;Boost::timer;Boost::chrono
> SPYDRPICK_DEPENDENCIES setup: Boost is enabled
> SPYDRPICK_DEPENDENCIES setup: check for TBB
> SPYDRPICK_DEPENDENCIES setup: found TBB interface v
>                               include dirs: 
>                               libraries: 
> SPYDRPICK_DEPENDENCIES setup: TBB is enabled
> SPYDRPICK_DEPENDENCIES setup: check for Apegrunt
> APEGRUNT setup: Boost is enabled
> APEGRUNT setup: CUDA is DISABLED
> SPYDRPICK_DEPENDENCIES setup: found Apegrunt
>                               include dir: /Users/danawang/Documents/SpydrPick/externals/apegrunt/include
>                               library: /Users/danawang/Documents/SpydrPick/build/lib/libapegrunt.a
> SPYDRPICK_DEPENDENCIES setup: Apegrunt is enabled
> -- Configuring done
> CMake Error at src/CMakeLists.txt:109 (add_executable):
>   Target "SpydrPick" links to item "-Wl,-Bdynamic " which has leading or
>   trailing whitespace.  This is now an error according to policy CMP0004.
> 
> 
> CMake Error at src/CMakeLists.txt:109 (add_executable):
>   Target "SpydrPick" links to item "-Wl,-Bdynamic " which has leading or
>   trailing whitespace.  This is now an error according to policy CMP0004.
> 
> 
> CMake Error at src/CMakeLists.txt:109 (add_executable):
>   Target "SpydrPick" links to item "-Wl,-Bdynamic " which has leading or
>   trailing whitespace.  This is now an error according to policy CMP0004.
> 
> 
> -- Generating done
> CMake Generate step failed.  Build files cannot be regenerated correctly.

I do not know which step is wrong.

Many thanks,
Dana

**Comment by santeripuranen** [comment]
Hi Dana,

Well, yeah, it appears that the CMake project configuration wasn't quite in sync with my local copy.. sorry about that. Try pulling from 'main' again and see if it works.

Best regards,
Santeri
