### ISSUE TITLE
About Simulate Data

### ISSUE THREAD

**Issue by Riffleriver** [santeripuranen/SpydrPick#9]
Hello Santeri, thanks for providing this efficient analysis tool~ We are very interested in using SpydrPick to detect bacterial epistasis, espicially the 'Simulated data' part. Would you mind providing the simulated data and the source code about how to generate this simulated data? I will deeply appreciate it~

**Comment by santeripuranen** [comment]
Hi,

Unfortunately I don't have the simulated data handy at the moment.. the simulations were performed by a colleague who also created the simulator. The relevant code should be available [here](https://github.com/brian-arnold/Haploid_fwdpp). Hope you find it useful.

Cheers,
Santeri

**Comment by Riffleriver** [comment]
> Hi,
> 
> Unfortunately I don't have the simulated data handy at the moment.. the simulations were performed by a colleague who also created the simulator. The relevant code should be available [here](https://github.com/brian-arnold/Haploid_fwdpp). Hope you find it useful.
> 
> Cheers, Santeri

Thank you so much for your reply~ I will check that link~ 

Best,

Wenxuan
